#!/bin/sh

function fix_border {
	if [ "$TERM" = "xterm-kitty" ]; then
		kitten @ set-spacing padding=0
		"$@"
		kitten @ set-spacing padding=default
	else
		"$@"
	fi
}

function nvims() {
  items=("default")
  config=$(printf "%s\n" "${items[@]}" | fzf --prompt=" Neovim Config  " --height=~50% --layout=reverse --border --exit-0)
  if [[ -z $config ]]; then
    echo "Nothing selected"
    return 0
  elif [[ $config == "default" ]]; then
    config=""
  fi
  NVIM_APPNAME=$config nvim $@
}

for cmd in vi vim nvim nano tmux ; do
	alias "$cmd"="fix_border $cmd"
done; unset cmd
